### ISSUE TITLE
 JSON FORMAT ISSUE

### ISSUE THREAD

**Issue by sojugeorge** [armosec/kubescape#62] opened 2021-09-06 19:18 UTC
JSON format commands are not working in GITLAB 

kubescape scan framework nsa --exclude-namespaces kube-system,kube-public --format json --output results.json 

Im not getting the output as json file. It's still showing me the same normal output.

Also when i tried in local, the json format is not coming in a correct way.

@dwertent

**Comment by dwertent** [comment] 2021-09-09 06:29
@sojugeorge Did you reinstall Kubescape (the json support is a later release)?
I tried to reproduce your issue without any success.

Can you please provide more relevant information. Are you using workflows? If so, can you please share the workflow?

Thank you

**Comment by victorca25** [comment] 2021-09-09 07:22
I had a JSON issue and was in fact using an older version, so the output was just the normal output until I upgraded.
Another thing is that if the command is executed multiple times with the same "results.json" output file, results are appended to the file and it can't later be opened as a JSON, unless you first split it into multiple JSONs.

**Comment by dwertent** [comment] 2021-09-09 08:04
@victorca25 Thank you.

The issue where the data is appended to the existing file will be fixed very soon :)

**Comment by sojugeorge** [comment] 2021-09-09 08:35
`kubescape scan framework nsa --exclude-namespaces kube-system,kube-public --format json` This command is not showing a proper json format.

if i add jq command i can make it in a correct format. 

Can we get the output in a proper json format @dwertent

**Comment by dwertent** [comment] 2021-09-09 08:56
@sojugeorge The output json is valid. If you wish to pretty-print the json you can use `jq`, `python`, etc.

Run kubescape with the `--silent` flag->
```
kubescape scan framework nsa --exclude-namespaces kube-system,kube-public --format json --silent |  jq .
```

**Comment by dwertent** [comment] 2021-09-09 20:25
Closed since non-pretty print json is the desired behavior

**Closed by dwertent** 2021-09-09 20:25 UTC
